apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: csvserver

namespace: csvserver

commonLabels:
  app: csvserver

configMapGenerator:
- name: csvinput
  files:
  - input.csv
  options:
   disableNameSuffixHash: true

resources:
- namespace.yaml  
- deployment.yaml 
- service.yaml

