apiVersion: v1
kind: Service
metadata:
  name: csvserver-svc
spec:
  selector:
    app: csvserver
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: csvserver
    protocol: TCP
    port: 80
    targetPort: 9300
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.